name: Post to Slack
on:
  push:
    branches:
      - test/actions

jobs:
  post_to_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Generate message
        run: |
          
      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_APP_SECRET }}
          payload: |
            channel: C04PGT140DD
            text: "howdy <@U04PGT12X1V>! [マニュアル](https://example.com)"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "New Paid Time Off request from <example.com|Fred Enriquez>\n\n<https://example.com|View request>"