name: Post to Slack
on:
  push:
    branches:
      - test/actions

jobs:
  post_to_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Generate message
        id: gen_message
        run: |
          message=`cat<<-EOT
            \\\`コードブロック\\\`
            こんにちは
            おげんきですか。
            ● これはリストです
            <https://google.com|Google>
            <@U04PGT12X1V>!
          EOT`

          echo 'message<<EOT' >> $GITHUB_OUTPUT
          echo "$message" >> $GITHUB_OUTPUT
          echo 'EOT' >> $GITHUB_OUTPUT
          
      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_APP_SECRET }}
          payload: |
            channel: C04PGT140DD
            markdown_text: |
            ${{ steps.gen_message.outputs.message }}